name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker run -t --rm -v $PWD:/data -w /data maven:3-openjdk-8-slim mvn clean test
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.1
      with:
        path: target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
